from rest_framework_simplejwt.serializers import TokenObtainPairSerializers
from rest_framework_simplejwt.settings import api_settings
from django.contrib.auth.models import update_last_login
from core.user.serializers import UserSerializer
